# Generated by Django 4.2.1 on 2023-06-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
