# Generated by Django 4.2.1 on 2023-06-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='current',
            field=models.BooleanField(verbose_name='активная'),
        ),
    ]
