# Generated by Django 4.2.1 on 2023-06-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=False, verbose_name='опубликован'),
        ),
    ]
